Define TOOL_REPO and CODE_REPO

diff --git a/.github/workflows/build-documents.yml b/.github/workflows/build-documents.yml
--- a/.github/workflows/build-documents.yml
+++ b/.github/workflows/build-documents.yml
@@ -49,7 +49,21 @@ jobs:
     runs-on: ubuntu-24.04
     steps:
 
-      # STEP 0: Define LANG, MT_X, owasp_pdf parameters
+      # STEP 1: Define system parameters
+      - name: Define TOOL_REPOSITORY and CODE_REPOSITORY
+        run: |
+          # production
+          # echo "CODE_REPO=OWASP" >> $GITHUB_ENV
+          # echo "CODE_DIR=AISVS" >> $GITHUB_ENV
+          # test bed
+          echo "CODE_REPO=tetsuoseto" >> $GITHUB_ENV
+          echo "CODE_DIR=AISVS" >> $GITHUB_ENV
+          #-------------------------
+          # default tool location; will be updated if self-servable
+          echo "TOOL_REPO=tetsuoseto" >> $GITHUB_ENV
+          echo "TOOL_DIR=Tenzing" >> $GITHUB_ENV
+
+      # STEP 2: Define LANG, MT_X, owasp_pdf parameters
       - name: Read owasp_pdf parameters
         if: ${{ startsWith(github.event.issue.title, 'Document Build Request') }}
         env:
@@ -57,12 +71,12 @@ jobs:
         run: |
           IFS=',' read -ra PARAMS <<< $EVENT_COMMENT_BODY
           if echo ${PARAMS[0]}; then
-            echo "LANG=${PARAMS[0]}" | tr -d " " >> $GITHUB_ENV
+            echo "LANG=${PARAMS[0]}" | tr -d " " >> $GITHUB_ENV;
           else
             echo "LANG=" >> $GITHUB_ENV;
           fi
           if echo ${PARAMS[1]}; then
-            echo "MT_X=${PARAMS[1]}" | tr -d " " >> $GITHUB_ENV
+            echo "MT_X=${PARAMS[1]}" | tr -d " " >> $GITHUB_ENV;
           else
             echo "MT_X=" >> $GITHUB_ENV;
           fi
@@ -76,7 +90,7 @@ jobs:
           if [[ ${{ env.LANG }} =~ ^[a-z]{2}-[A-Z]{2}$ ]]; then
             :
           else
-            echo "LANG=" >> $GITHUB_ENV
+            echo "LANG=" >> $GITHUB_ENV;
           fi
       - name: Adjust MT_X
         if: ${{ env.LANG != '' && env.MT_X != '' && !contains(fromJSON('["mt", "x", "b"]'), env.MT_X) }}
@@ -87,48 +101,46 @@ jobs:
           TRANSLATE_ACCESS_KEY: ${{ secrets.TRANSLATE_ACCESS_KEY }}
         run: |
           if ${{ env.LANG == '' }}; then
-            echo "The command '$EVENT_COMMENT_BODY' is invalid."
-            exit 1
+            echo "The command '$EVENT_COMMENT_BODY' is invalid.";
+            exit 1;
           fi
           if ${{ env.MT_X == 'mt' && env.TRANSLATE_ACCESS_KEY == '' }}; then
-            echo "MT is not supported in this repository."
-            exit 1
+            echo "MT is not supported in this repository.";
+            exit 1;
           fi
           if ${{ env.MT_X == 'mt' && (
             github.event.comment.author_association != 'OWNER')
           }}; then
-            echo "MT is not allowed. Pls consult with the repo maintainer."
-            exit 1
+            echo "MT is not allowed. Pls consult with the repo maintainer.";
+            exit 1;
           fi
           if ${{ env.MT_X == 'b' && (
             github.event.comment.author_association != 'OWNER')
           }}; then
-            echo "B is not allowed. Pls consult with the repo maintainer."
-            exit 1
+            echo "B is not allowed. Pls consult with the repo maintainer.";
+            exit 1;
           fi
 
-      # STEP 1: Check out the repository code; we'll commit bld result/PR to it
-      # We'll download the Tenzing tool on to it.
+      # STEP 3: Check out the repository code; we'll commit bld result/PR to it
+      # We'll download the tool on to it.
       - name: Check out repository code
         if: ${{ env.LANG != '' }}
         uses: actions/checkout@v4
         with:
-          # test bed
-          repository: tetsuoseto/AISVS
-          # production
-          # repository: OWASP/AISVS
+          repository: ${{ env.CODE_REPO }}/${{ env.CODE_DIR }}
           ref: main
       - name: Check if linux.zip exists
         if: ${{ env.LANG != '' }}
         run: |
           if [ -f ${{ github.workspace }}/1.0/docgen/linux.zip ]; then
-            echo "LINUX_ZIP_EXISTS=yes" >> $GITHUB_ENV;
-            cp -rf ${{ github.workspace }}/1.0/docgen/linux.zip ${{ github.workspace }}/main.zip;
+            echo "TOOL_SELF_SERVABLE=yes" >> $GITHUB_ENV;
+            echo "TOOL_REPO=${{ env.CODE_REPO }}" >> $GITHUB_ENV;
+            echo "TOOL_DIR=${{ env.CODE_DIR }}" >> $GITHUB_ENV;
           else
-            echo "LINUX_ZIP_EXISTS=no" >> $GITHUB_ENV;
+            echo "TOOL_SELF_SERVABLE=no" >> $GITHUB_ENV;
           fi
 
-      # STEP 2: Define target branch name
+      # STEP 4: Define target branch name
       - name: Define target branch name with MT_X
         if: ${{ env.LANG != '' && env.MT_X != '' }}
         run: |
@@ -140,7 +152,7 @@ jobs:
           MAIN_SHA="PDF_${{ env.LANG }}_${{ github.sha }}"
           echo "TARGET_BRANCH_NAME=$MAIN_SHA" >> $GITHUB_ENV
 
-      # STEP 3: Check if the target branch exists
+      # STEP 5: Check if the target branch exists
       - name: Check if the target branch exists
         if: ${{ env.LANG != '' }}
         run: |
@@ -153,46 +165,32 @@ jobs:
             echo "BRANCH_EXISTS=no" >> $GITHUB_ENV;
           fi
 
-      # STEP 4: Prep for build
-      - name: Download the tool as a zip file
+      # STEP 6: Prep for build
+      - name: Download the tool
         if: ${{ env.LANG != '' && env.BRANCH_EXISTS == 'no' }}
         run: |
-          # serve from the tool repository
-          curl -L -o main.zip "https://github.com/tetsuoseto/Tenzing/archive/refs/heads/main.zip"
-          # self serve
-          # curl -L -o main.zip "https://github.com/tetsuoseto/AISVS/archive/refs/heads/main.zip"
-      - name: Unzip the tool zip file
+          curl -L -o main.zip "https://github.com/${{ env.TOOL_REPO }}/${{ env.TOOL_DIR }}/archive/refs/heads/main.zip"
+      - name: Unzip the curled main.zip file
         if: ${{ env.LANG != '' && env.BRANCH_EXISTS == 'no' }}
         run: |
-          ls -la ${{ github.workspace }}
-          unzip main.zip -d UNZIPPED
-      - name: List the tool files checked out to the build workspace
+          unzip -qq main.zip -d UNZIPPED
+      - name: Copy plug-in module and owasp_pdf executable
         if: ${{ env.LANG != '' && env.BRANCH_EXISTS == 'no' }}
         run: |
-          ls -la ${{ github.workspace }}
-      - name: Copy owasp_pdf and plug-in module
-        if: ${{ env.LANG != '' && env.BRANCH_EXISTS == 'no' }}
-        run: |
-          # serve from the tool repository
-          cd UNZIPPED/Tenzing-main/
-          # self serve
-          # cd UNZIPPED/AISVS-main/1.0/docgen
+          if ${{ env.TOOL_SELF_SERVABLE == 'yes' }}; then
+            cd UNZIPPED/${{ env.TOOL_DIR }}-main/1.0/docgen;
+          else
+            cd UNZIPPED/${{ env.TOOL_DIR }}-main;
+          fi
           unzip linux.zip
-          cd linux
-          pwd
-          ls -la
-          cp owasp_pdf ${{ github.workspace }}/1.0/docgen/owasp_pdf
-          # serve from the tool repository
-          cd ../BldEnv20241124
-          # self serve
-          # cd ..
-          pwd
-          ls -la
+          cp -f linux/owasp_pdf ${{ github.workspace }}/1.0/docgen
+          if ${{ env.TOOL_SELF_SERVABLE == 'no' }}; then
+            cd BldEnv20241124;
+          fi
           cp -rf owasp_pdf_data_ASV ${{ github.workspace }}/1.0/docgen
           cp -f owasp_pdf_register_ASV_plugin.py ${{ github.workspace }}/1.0/docgen
           cp -rf owasp_pdf_data_ZZZ ${{ github.workspace }}/1.0/docgen
           cp -f owasp_pdf_register_ZZZ_plugin.py ${{ github.workspace }}/1.0/docgen
-
       - name: List files under 1.0/docgen
         if: ${{ env.LANG != '' && env.BRANCH_EXISTS == 'no' }}
         run: |
@@ -204,7 +202,7 @@ jobs:
           cd ${{ github.workspace }}/1.0/docgen/asv
           ls -la
 
-      # STEP 5: Build
+      # STEP 7: Build
       - name: Call ./owasp_pdf with ${{ env.LANG }}
         if: ${{ env.LANG != '' && env.BRANCH_EXISTS == 'no' && env.MT_X == '' }}
         run: |
@@ -230,7 +228,7 @@ jobs:
           cd ${{ github.workspace }}/1.0/docgen
           ./owasp_pdf -s -y -l ASV_${{ env.LANG }}
 
-      # STEP 6: Delete used files
+      # STEP 8: Delete used files
       - name: Delete used files
         if: ${{ always() && env.LANG != '' && env.BRANCH_EXISTS == 'no' }}
         run: |
@@ -249,7 +247,7 @@ jobs:
           cp ${{ github.workspace }}/SAVED/owasp_pdf_register_ZZZ_plugin.py ${{ github.workspace }}/1.0/docgen;
           rm -rf ${{ github.workspace }}/SAVED
 
-      # STEP 7: Clean up
+      # STEP 9: Clean up
       - name: Clean up
         if: ${{ always() && env.LANG != '' && env.BRANCH_EXISTS == 'no' }}
         run: |
@@ -258,7 +256,7 @@ jobs:
           rm -rf UNZIPPED
           rm -f main.zip
 
-      # STEP 8: Commit and PR
+      # STEP 10: Commit and PR
       - name: Commit the changes
         if: ${{ env.LANG != '' && env.BRANCH_EXISTS == 'no' }}
         env:
